# https://goreleaser.com
project_name: crop

# Build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/l3uddz/crop/runtime.Version={{ .Version }}"
      - -X "github.com/l3uddz/crop/runtime.GitCommit={{ .ShortCommit }}"
      - -X "github.com/l3uddz/crop/runtime.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath

# MacOS Universal Binaries
universal_binaries:
  -
    replace: true

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"